Update init-letsencrypt.sh.template
Update to check for docker instead of docker-compose with deprecation of docker-compose

diff --git a/ssl/init-letsencrypt.sh.template b/ssl/init-letsencrypt.sh.template
--- a/ssl/init-letsencrypt.sh.template
+++ b/ssl/init-letsencrypt.sh.template
@@ -2,8 +2,8 @@
 # Adapted from https://github.com/wmnnd/nginx-certbot
 # Run this from the root of the Autolab docker installation directory (not from the ssl subdirectory)
 
-if ! [ -x "$(command -v docker compose)" ]; then
-  echo 'Error: docker compose is not installed.' >&2
+if ! [ -x "$(command -v docker)" ]; then
+  echo 'Error: docker is not installed.' >&2
   exit 1
 fi
 
